# Generated by Django 3.2.24 on 2024-04-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_delete_userprofile'),
        ('profiles', '0005_auto_20240420_0033'),
    ]

    operations = [
    ]
